version: '3.0'
services:
  server:
    container_name: laravel-docker
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
  
  mysql:
    container_name: mysql_database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
    - 3309:3306
    volumes:
      - ./mysql:/var/lib/mysql
    depends_on:
      - server

  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:     
    - PMA_ARBITRARY=1
    depends_on:
      - server
      - mysql
